### ISSUE TITLE
Menu entry for Shows fails to retrieve list of shows

### ISSUE THREAD

**Issue by gedakc** [micahg/plugin.video.cbc#14]
Recently the **Shows** menu entry in the CBC add-on stopped retrieving a list of shows.

Version information:

- CBC Add-on from Kodi repository (v4.0.6+matrix.1)
- Kodi Matrix 19.1 running on 2017 NVidia Shield

Relevant lines from kodi.log file

```
2021-08-20 09:49:53.010 T:13726   ERROR <general>: plugin.video.cbc: (getShows) None returns 426 status
2021-08-20 09:49:53.024 T:13726   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'NoneType' object is not subscriptable
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cbc/default.py", line 249, in <module>
                                                       showsMenu(values)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cbc/default.py", line 178, in showsMenu
                                                       isVideo = True if 'video' in show_list[0] else False
                                                   TypeError: 'NoneType' object is not subscriptable
                                                   -->End of Python script error report<--
                                                   
2021-08-20 09:49:53.303 T:13726    INFO <general>: Python interpreter stopped
2021-08-20 09:49:53.314 T:13725   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.cbc/?menu=Shows
2021-08-20 09:49:53.324 T:13662   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.cbc/?menu=Shows) failed
```

The result is that this add-on is no longer able to list and play CBC shows.

**Comment by micahg** [comment]
Yup -- missed a None check.

**Comment by micahg** [comment]
But also the API version needed to be updated. @gedakc, I've uploaded 4.0.7+matrix.1 to my personal repo github.com:micahg/repo.micahg.git.

It seems to be working on my firestick -- can you confirm? If its good for you I'll put in a PR.

**Comment by gedakc** [comment]
Thanks @micahg for the quick response.

I noticed some recent code updates in the **v4_0_8** branch so that is what I downloaded.

I am pleased to say that these updates enabled me to list and play shows on Kodi Matrix 19.1 on my 2017 NVidia Shield.  Great work!

On a different note were you looking for some help with git commands to get code development back onto the **master** branch or a non-version named branch?

**Comment by micahg** [comment]
Nope -- all good. I'll do a PR to get it onto the main repo soonish.

**Comment by gedakc** [comment]
Cool.  Thanks again for making it possible to watch CBC shows again.  :-)

**Comment by micahg** [comment]
You're welcome.

PR is over there: https://github.com/xbmc/repo-plugins/pull/3706

**Comment by micahg** [comment]
Fix merged into the main repo.
