### ISSUE TITLE
After logout, authentication fails with 4.0.11+matrix.1

### ISSUE THREAD

**Issue by gedakc** [micahg/plugin.video.cbc#22]
After logout, the add-on fails to re-authenticate and will fail to play videos.

## Steps to Reproduce

1. Make a backup of the add-on configuration files (includes authentication and cookies).  These will be used to restore add-on functionality later.

        $ tar -cvf cbc-config-backup.tar.gz .kodi/userdata/addon_data/plugin.video.cbc/
        .kodi/userdata/addon_data/plugin.video.cbc/
        .kodi/userdata/addon_data/plugin.video.cbc/cookies
        .kodi/userdata/addon_data/plugin.video.cbc/authorization
        .kodi/userdata/addon_data/plugin.video.cbc/settings.xml

2. In the add-on choose **Configure** then **Logout**

3. Confirm that the authorization and cookies files have been removed.

        $ ls -l .kodi/userdata/addon_data/plugin.video.cbc/
        total 4
        -rw-r--r-- 1 osmc osmc 460 Oct  8 14:17 settings.xml

4. In the add-on try **Open**

   Notice a message like "Authorizing device..." is briefly displayed followed by another error log message report shortly thereafter.

   An examination of the log file indicates a failure to establish a new connections with host='api-cbc.cloud.clearleap.com'

   See Appendix A for relevant contents of the .kodi/temp/kodi.log.

   **At this time the add-on will not display a list of shows.**

5. Fix the add-on by restoring the backup of the add-on configuration files.

        $ tar -xvf cbc-config-backup.tar.gz
        drwxr-xr-x osmc/osmc         0 2021-09-23 15:26 .kodi/userdata/addon_data/plugin.video.cbc/
        -rw-r--r-- osmc/osmc        79 2021-09-23 15:27 .kodi/userdata/addon_data/plugin.video.cbc/cookies
        -rw-r--r-- osmc/osmc      2053 2021-09-23 15:26 .kodi/userdata/addon_data/plugin.video.cbc/authorization
        -rw-r--r-- osmc/osmc       460 2021-09-23 15:26 .kodi/userdata/addon_data/plugin.video.cbc/settings.xml

   Try to **Open** the add-on and it once again works.

## Appendix A: Snipped of .kodi/temp/kodi.log log file

```
2021-10-08 14:18:47.382 T:569   WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-10-08 14:18:47.391 T:396      INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2021-10-08 14:18:47.400 T:569     ERROR <general>: plugin.video.cbc: Unable to load cookies: [Errno 2] No such file or directory: '/home/osmc/.kodi/userdata/addon_data/plugin.video.cbc/cookies'
2021-10-08 14:18:47.542 T:569     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.ConnectionError'>
                                                   Error Contents: HTTPSConnectionPool(host='api-cbc.cloud.clearleap.com', port=443): Max retries exceeded with url: /cloffice/client/identities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x5b6861b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 170, in _new_conn
                                                       (self._dns_host, self.port), self.timeout, **extra_kw
                                                     File "/home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/util/connection.py", line 73, in create_connection
                                                       for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
                                                     File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
                                                       for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
                                                   socket.gaierror: [Errno -2] Name or service not known
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 706, in urlopen
                                                       chunked=chunked,
                                                     File "/home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 382, in _make_request
                                                       self._validate_conn(conn)
                                                     File "/home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 1010, in _validate_conn
                                                       conn.connect()
                                                     File "/home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 353, in connect
                                                       conn = self._new_conn()
                                                     File "/home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 182, in _new_conn
                                                       self, "Failed to establish a new connection: %s" % e
                                                   urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x5b6861b0>: Failed to establish a new connection: [Errno -2] Name or service not known
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 449, in send
                                                       timeout=timeout
                                                     File "/home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 756, in urlopen
                                                       method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
                                                     File "/home/osmc/.kodi/addons/script.module.urllib3/lib/urllib3/util/retry.py", line 574, in increment
                                                       raise MaxRetryError(_pool, url, error or ResponseError(cause))
                                                   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api-cbc.cloud.clearleap.com', port=443): Max retries exceeded with url: /cloffice/client/identities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x5b6861b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.cbc/default.py", line 288, in <module>
                                                       plugin.run()
                                                     File "/home/osmc/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/home/osmc/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/home/osmc/.kodi/addons/plugin.video.cbc/default.py", line 277, in main_menu
                                                       authorize()
                                                     File "/home/osmc/.kodi/addons/plugin.video.cbc/default.py", line 48, in authorize
                                                       if not cbc.authorize(username, password, prog.update):
                                                     File "/home/osmc/.kodi/addons/plugin.video.cbc/resources/lib/cbc.py", line 37, in authorize
                                                       r = self.session.get(self.IDENTITIES_URL)
                                                     File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 555, in get
                                                       return self.request('GET', url, **kwargs)
                                                     File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 542, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                     File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 655, in send
                                                       r = adapter.send(request, **kwargs)
                                                     File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 516, in send
                                                       raise ConnectionError(e, request=request)
                                                   requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api-cbc.cloud.clearleap.com', port=443): Max retries exceeded with url: /cloffice/client/identities (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x5b6861b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
                                                   -->End of Python script error report<--
                                                   
2021-10-08 14:18:47.961 T:569      INFO <general>: Python interpreter stopped
2021-10-08 14:18:47.969 T:567     ERROR <general>: GetDirectory - Error getting plugin://plugin.video.cbc/
2021-10-08 14:18:47.979 T:396     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.cbc/) failed
```

**Comment by gedakc** [comment]
I've learned a bit more about this issue.

It seems that only the most recent seasons are able to successfully play in the add-on.  For example:
- Downton Abbey S0**6**E01 will play.
- Downton Abbey S0**1**E01 will fail to play.

From this I infer that the authentication is not succeeding, even though I am using the exact same credentials as on the GEM web site which does permit playing all seasons of this show.

**Comment by micahg** [comment]
Yes. It's an authorization issue. I'll fix it.

**Comment by gedakc** [comment]
That would be awesome!  I am available to test as needed.

**Comment by micahg** [comment]
TY, do you have my personal repo setup? I'll push there first.

**Comment by gedakc** [comment]
Yes, I have cloned copy of the repo and I am familiar with git.

**Comment by micahg** [comment]
OK, 4.0.13 has the fix -- you don't git, you can just install my repo (https://github.com/micahg/repo.micahg)

**Comment by gedakc** [comment]
Good work getting authentication working again.  I tested with 4.0.13+matrix and now I can play both S01E01 and S06E01 of Downton Abbey.  :-)

One regression I noticed is that I am no longer able to display Closed Captions.

For example with Ghosts S01E01, I was able to turn on Closed Captioning using 4.0.11+matrix.1.

However with 4.0.13+matrix.1 I seem to be unable to get this to work.

**Comment by micahg** [comment]
Not too sure about that... I don't really mess with the video -- CC is all built right into the stream......  I'll take a look when I have time.
