### ISSUE TITLE
Unable to browse show listing level of categories

### ISSUE THREAD

**Issue by twhitehead** [micahg/plugin.video.cbc#41]
The last level of menus started fail in the last month or so. The python log says
```
2024-11-08 20:55:31.752 T:4074766   error <general>: GetDirectory - Error getting plugin://plugin.video.cbc/gem/categories/shows-categories-documentary
2024-11-08 20:55:31.762 T:4074592   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.cbc/gem/categories/shows-categories-documentary) failed
2024-11-08 20:55:34.695 T:4074770   error <general>: plugin.video.cbc: Unable to load cookies: [Errno 2] No such file or directory: '/home/kodi/.kodi/userdata/addon_data/plugin.video.cbc/cookies'
2024-11-08 20:55:35.140 T:4074770   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'items'
                                                   Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/plugin.video.cbc/default.py", line 345, in <module>
                                                       plugin.run()
                                                     File "/home/kodi/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/home/kodi/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/home/kodi/.kodi/addons/plugin.video.cbc/default.py", line 286, in gem_category_menu
                                                       for show in category['items']:
                                                                   ~~~~~~~~^^^^^^^^^
                                                   KeyError: 'items'
                                                   -->End of Python script error report<--
```
The only way I can get to the list of episodes to watch thing is to search for the program and then access it through the search results. Live TV also still works.

**Comment by twhitehead** [comment]
Thanks. I'll give that a go. :+1: 

I actually ran into what sounds a lot like the bug you linked too. You could hear skips in the sound. Originally it would exit playback after a bit too. I updated the machine to the latest distro release and then the exiting resolved, but the skips were still there.

I was going through the setting and noticed the option to choose the video player. I switched to from the default ffmpeg to winevine (going off memory for the names, so should double check) and the problem went away.

**Comment by twhitehead** [comment]
Changing the player to input adaptive (not winevine) was what resolved the audio glitching issues. I will try the catalog_v2 version when I have a moment and see if that resolves the catalog issues.

**Comment by twhitehead** [comment]
Just a note that I finally tried this and `catalog_v2` resolved the catalog issues. Thanks very much! 👍 

I read through the links you provided, and tried _Better Things_ too
* audio is okay,
* able to seek around without issues,
* default high resolution steam video doesn't work, but
* lower resolution one does (`m` Menu → Video Stream → 640x360).

So, not 100% ideal, but seems there is at least a way to play everything. For what it is worth, it seems the shows that do play without changing the steam, are the ones that don't have a high resolution one.

Also, with my current system (NixOS/24.05) it seems I not longer have any audio glitches with FFMPEG.

**Comment by twhitehead** [comment]
Had been meaning to mention that too (that all the episodes in all the later seasons are actually the first season). Thanks!

**Comment by micahg** [comment]
Still doesn't work for me. If you browse to:

- Comedies
- Better Things (thats one of the ones that I can't get to play back well)
- Season 1
- Sam/Pilot

Does that work for y'all? My feeling is that if over time more and more of the content becomes inaccessible AND the Gem app is widely available, I question the value of this addon.

**Comment by micahg** [comment]
interesting - i didn't even realize you could change streams. Oddly I don't get a "H264 1280x720 3400148 bps" stream... which show/episode was that for?

**Comment by ealehr** [comment]
> Still doesn't work for me. If you browse to:
> 
> * Comedies
> * Better Things (thats one of the ones that I can't get to play back well)
> * Season 1
> * Sam/Pilot
> 
> Does that work for y'all? My feeling is that if over time more and more of the content becomes inaccessible AND the Gem app is widely available, I question the value of this addon.

I find your addon extremely valuable and far better than the CBC Gem app currently available on my Samsung TV.

I am running the feat/catalog_v2 branch (plugin.video.cbc-4.0.20+matrix.1.zip installed from your repo) on a RPi5 under the LibreELEC version of Kodi (set to use inputstream.adaptive) in the addon settings and I can play most of the shows I am looking for by browsing the "Shows" section of the addon's main menu (for example)...

The Nature of Things, Animal Control, Murdoch Mysteries, Son of a Critch, This Hour Has 22 Minutes, Wild Cards, Call the Midwife

... all play perfectly for me.

My only issue is the same as that reported by kyl416 and twhitehead (episodes listed in all seasons are the same as the first).

Personally, I'm not interested in programs re-broadcast by the CBC from other (DRM protected) sources, only CBC original content.

Also, I can watch CBC News Network (Live Channels) with my free CBC account (not possible on the Gem app without premium).

Please stay with us and keep up the good fight (your efforts are appreciated).

**Comment by twhitehead** [comment]
I have, and will be, unable to test anything for a while as my system is in storage due to renovations. Once it is back out I can test _Better Things_. Thanks!

**Comment by ealehr** [comment]
Is it possible to get the following PR's merged (into the main branch) as they appear to resolve this issue?
https://github.com/micahg/plugin.video.cbc/pull/40
https://github.com/micahg/plugin.video.cbc/pull/42
Thanks.

**Comment by twhitehead** [comment]
This is great news! Thanks everyone. 👍
